services:
  # Node Server
  client:
    build:
      context: ./client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app/src
      - /app/src/node_modules
    depends_on:
      - server
    networks:
      - shipentegra

  # Node Server
  server:
    build:
      context: ./server
    env_file:
      - server/.env
    ports:
      - 8888:8888
    volumes:
      - ./server:/app/src
      - /app/src/node_modules
      - ./server/uploads:/app/src/uploads

    depends_on:
      - mysql
      - redis
    networks:
      - shipentegra

  # Database Server
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=shipentegra
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - shipentegra

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - shipentegra

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - shipentegra

  redis-ui:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=${REDIS_PASSWORD}
    ports:
      - 8002:80
    depends_on:
      - redis
    networks:
      - shipentegra

  worker:
    build:
      context: ./server
    command: node workers/task-worker.js
    volumes:
      - ./server:/app/src
      - /app/src/node_modules
    env_file:
      - server/.env
    depends_on:
      - redis
    networks:
      - shipentegra

  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - shipentegra

  mongoo-express:
    image: mongo-express:1
    ports:
      - 8003:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - shipentegra

volumes:
  db-data:
  redis-data:
  mongo-data:


networks:
  shipentegra:
    driver: bridge
